### PR TITLE
fixed ironmq v3 agent

### PR DESCRIPTION
**Pull request by ulandj**

### CODE REVIEW

**Comment by ulandj** [comment]
@thousandsofthem @carimura @rkononov could you please take a look?

**Comment by thousandsofthem** [comment]
Code lgtm. Do you remember how config values are set? Since config is changed, counterpart should be changed as well

**Comment by thousandsofthem** [comment]
I think they are set via uploader worker and/or hud/newrelic page

**Comment by thousandsofthem** [comment]
Also - port is defined but schema (http/https) is not

**Comment by thousandsofthem** [comment]
also please compare with code there: https://github.com/iron-io/internal-workers/tree/master/other_workers/new_relic_agents_installer

**Comment by ulandj** [comment]
@thousandsofthem 
> Do you remember how config values are set?
1) via uploader worker https://github.com/iron-io/internal-workers/pull/227
2) via hud code details page -> `config` section


> Also - port is defined but schema (http/https) is not
done

**Pull request merged**
